name: "g1"
joint_names:
  - "L_LEG_HIP_PITCH"
  - "L_LEG_HIP_ROLL"
  - "L_LEG_HIP_YAW"
  - "L_LEG_KNEE"
  - "L_LEG_ANKLE_PITCH"
  - "L_LEG_ANKLE_ROLL"
  - "R_LEG_HIP_PITCH"
  - "R_LEG_HIP_ROLL"
  - "R_LEG_HIP_YAW"
  - "R_LEG_KNEE"
  - "R_LEG_ANKLE_PITCH"
  - "R_LEG_ANKLE_ROLL"
  - "WAIST_YAW"
  - "WAIST_ROLL"
  - "WAIST_PITCH"
foot_names:
  - "L_FOOT"
  - "R_FOOT"
kp: 100.0
kd: 2.0
standing_cfg: [
  -0.05, 0.0, 0.0, 0.35, -0.3, 0.0,
  -0.05, 0.0, 0.0, 0.35, -0.3, 0.0,
  0.0, 0.0, 0.0,
]
lying_cfg: [
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0,
]
auto_damped_mode: true
