name: "x30u"
joint_names:
  - "FR_hip"
  - "FR_thigh"
  - "FR_calf"
  - "FL_hip"
  - "FL_thigh"
  - "FL_calf"
  - "RR_hip"
  - "RR_thigh"
  - "RR_calf"
  - "RL_hip"
  - "RL_thigh"
  - "RL_calf"
foot_names:
  - "FR_foot"
  - "FL_foot"
  - "RR_foot"
  - "RL_foot"
kp: 400.0
kd: 4.0
standing_cfg: [
  0.0, 0.773, -1.501,
  0.0, 0.773, -1.501,
  0.0, 0.773, -1.501,
  0.0, 0.773, -1.501,
]
lying_cfg: [
  0.0, 1.221, -2.618,
  0.0, 1.221, -2.618,
  0.0, 1.221, -2.618,
  0.0, 1.221, -2.618,
]
auto_damped_mode: false
kd_damped_mode: 10.0
